default:	MinWorkExampleMPI
all:	MinWorkExampleMPI

MinWorkExampleMPI: MinWorkExampleMPI.c Makefile
	mpicc MinWorkExampleMPI.c  -o MinWorkExampleMPI

clean:
	rm -f MinWorkExampleMPI MinWorkExampleMPI.o
